# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Python ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3'
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        arch:
          - 'x64'
        include:
          - {"os": "windows-latest", "arch": "x86", "version": "3.7"}
          - {"os": "windows-latest", "arch": "x86", "version": "3.8"}
          - {"os": "windows-latest", "arch": "x86", "version": "3.9"}
          - {"os": "windows-latest", "arch": "x86", "version": "3.10"}
          - {"os": "windows-latest", "arch": "x86", "version": "3"}
    # The job environment.
    env:
      OS: ${{ matrix.os }}
      ARCH: ${{ matrix.arch }}
      PYTHON: ${{ matrix.version }}
    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '2'
      - name: Setup Python Environment
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.version }}
          architecture: ${{ matrix.arch }}
      - name: Display Python version
        run: python --version
      - name: Run Tests
        run: |
          python setup.py build
          python setup.py install
          #pip install coverage
          cd ~
          #coverage run -m unittest phamt.test
          python run -m unittest phamt.test
#      - name: Process Code Coverage
#        uses: codecov/codecov-action@v1
